<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLoSKuDV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLoSKuDV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLoSKuDV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLoSKuDV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLoSKuDV\App_KernelDevDebugContainer([
    'container.build_hash' => 'LoSKuDV',
    'container.build_id' => 'a31f955a',
    'container.build_time' => 1738884156,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLoSKuDV');
