<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMXj4qlG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMXj4qlG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMXj4qlG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMXj4qlG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMXj4qlG\App_KernelDevDebugContainer([
    'container.build_hash' => 'MXj4qlG',
    'container.build_id' => '3fa14690',
    'container.build_time' => 1738318809,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMXj4qlG');
